name: Windows Build

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            nasm
            diffutils
            vim
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libsndfile

      - name: Build FFmpeg
        run: |
          git clone --depth 1 --branch n7.0.1 https://github.com/FFmpeg/FFmpeg.git
          cd FFmpeg
          ./configure --disable-everything \
            --enable-decoder=cinepak \
            --enable-decoder=indeo3 \
            --enable-decoder=pcm_s16le \
            --enable-demuxer=avi \
            --enable-demuxer=wav \
            --enable-protocol=file \
            --enable-filter=scale \
            --enable-static \
            --disable-shared \
            --disable-doc \
            --extra-libs=-static \
            --extra-cflags=--static \
            --prefix=/mingw64
          make -j$(nproc)
          make install
          cd ..

      - name: Configure and Build Project
        run: |
          mkdir debug
          meson debug -Dbuildtype=debug
          ninja -C debug
          mkdir release
          meson release -Dbuiltype=release
          ninja -C release

      - name: Copy licenses
        run: |
          ls /mingw64/share/licenses
          mkdir dist
          cp -r /mingw64/share/licenses dist/
          cp fonts/*.license dist/licenses/

      - name: Package
        run: |
          cp release/ai5.exe LICENSE README.md dist/
          cp debug/ai5.exe dist/ai5-debug.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai5
          path: dist
          compression-level: 9
