name: Windows Build (MSYS2)

on:
  push:

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install ffmpeg-static via npm and add to PATH
        shell: bash 
        run: |
          npm install --prefix ./tools ffmpeg-static
          echo "$GITHUB_WORKSPACE/tools/node_modules/.bin" >> $GITHUB_PATH

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            nasm
            diffutils
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libsndfile

      - name: Configure and Build Project
        run: |
          mkdir build
          meson build
          ninja -C build